name: elestio/elestio
resources:
    elestio_service:
        subCategory: ""
        description: Elestio Service resource
        name: elestio_service
        title: elestio_service Resource - terraform-provider-elestio
